# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-02-25 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bdd_sites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(default=' ', max_length=400)),
                ('image_site', models.FileField(default='', upload_to='image_site/')),
                ('lien_site', models.CharField(default=' ', max_length=400)),
                ('archive', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site',
                'ordering': ['nom_site'],
            },
        ),
    ]
