# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-10 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bdd_chiffre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('nombre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Chiffres clé',
            },
        ),
        migrations.CreateModel(
            name='Bdd_evenement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(default=' ', max_length=400)),
                ('texte', models.TextField(default=' ')),
                ('img', models.FileField(upload_to='image_evenement/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Évenement',
            },
        ),
        migrations.CreateModel(
            name='Bdd_mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Mail',
            },
        ),
        migrations.CreateModel(
            name='Bdd_reseaux',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('lien', models.CharField(default=' ', max_length=400)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': 'Réseaux lien',
            },
        ),
    ]
