# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-12-11 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bdd_chiffre_anglais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(default=' ', max_length=400)),
                ('nombre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chiffres clés anglai',
                'ordering': ['id'],
            },
        ),
    ]
